import Link from "next/link";
import { ArchitectureDiagram } from "@/components/architecture-diagram";
import { SectionHeading } from "@/components/section-heading";
import { capabilities, experienceHighlights, impact, labs, principles, site } from "@/lib/site";

export default function Home() {
  return (
    <main>
      <section className="grid-field border-b border-[var(--line)]">
        <div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28 lg:py-36">
          <div className="reveal max-w-5xl">
            <div className="mb-8 flex flex-wrap items-center gap-2 text-xs">
              <span className="rounded-full border border-[var(--line)] bg-[var(--surface)] px-3 py-1.5">New York, NY</span>
              <span className="rounded-full border border-[var(--line)] bg-[var(--surface)] px-3 py-1.5">Forward Deployed / Applied AI</span>
              <span className="rounded-full border border-[var(--line)] bg-[var(--surface)] px-3 py-1.5">Enterprise AI systems</span>
            </div>
            <h1 className="text-balance text-5xl font-semibold tracking-[-0.055em] sm:text-6xl md:text-7xl lg:text-[88px] lg:leading-[0.98]">I build AI systems that survive contact with the enterprise.</h1>
            <p className="mt-8 max-w-3xl text-balance text-lg leading-8 text-[var(--muted)] md:text-xl">I connect models to live data, permissions, tools, and real workflows—then evaluate whether the system is reliable enough to ship and valuable enough to keep.</p>
            <div className="mt-9 flex flex-wrap gap-3"><Link href="/work/enterprise-ai-ops-agent" className="rounded-full bg-[var(--ink)] px-5 py-3 text-sm font-semibold text-[var(--bg)] transition hover:opacity-85">Explore flagship build ↗</Link><Link href="/labs" className="rounded-full border border-[var(--line)] bg-[var(--surface)] px-5 py-3 text-sm font-semibold transition hover:border-[var(--ink)]">Run agent demos</Link></div>
          </div>
          <div className="mt-20 grid gap-px overflow-hidden rounded-3xl border border-[var(--line)] bg-[var(--line)] md:grid-cols-4">{impact.map((item) => <div key={item.label} className="bg-[var(--surface)] p-6 md:p-7"><p className="text-3xl font-semibold tracking-[-0.04em]">{item.value}</p><p className="mt-2 text-sm font-medium">{item.label}</p><p className="mt-4 text-xs leading-5 text-[var(--muted)]">{item.detail}</p></div>)}</div>
        </div>
      </section>

      <section className="border-b border-[var(--line)]"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><SectionHeading eyebrow="What I do" title="Build the connective tissue between frontier models and real organizations." body="The hard part of enterprise AI is rarely the first model call. It is everything required to make that call trustworthy, useful, observable, and repeatable." /><div className="mt-12 grid gap-px overflow-hidden rounded-3xl border border-[var(--line)] bg-[var(--line)] md:grid-cols-2">{capabilities.map((cap) => <article key={cap.title} className="bg-[var(--surface)] p-7 md:p-9"><h3 className="text-xl font-semibold tracking-[-0.025em]">{cap.title}</h3><p className="mt-4 max-w-xl text-sm leading-7 text-[var(--muted)]">{cap.body}</p><div className="mt-6 flex flex-wrap gap-2">{cap.proof.map((item) => <span key={item} className="rounded-full bg-[var(--soft)] px-3 py-1.5 text-xs">{item}</span>)}</div></article>)}</div></div></section>

      <section id="work" className="border-b border-[var(--line)]"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><SectionHeading eyebrow="Featured proof" title="ContextOps: an enterprise AI operations agent." body="A public, subscription-free reference build for the kind of problems I solve in production: messy knowledge, authorization boundaries, tool calls, evaluation, and business impact." /><div className="mt-12"><ArchitectureDiagram /></div><div className="mt-8 grid gap-4 lg:grid-cols-[1.3fr_0.7fr]"><div className="rounded-3xl border border-[var(--line)] bg-[var(--surface)] p-7 md:p-9"><p className="font-mono text-xs uppercase tracking-[0.14em] text-[var(--signal)]">Why this project exists</p><h3 className="mt-4 text-2xl font-semibold tracking-[-0.03em]">A model demo is easy. A deployment is a systems problem.</h3><p className="mt-5 max-w-2xl text-sm leading-7 text-[var(--muted)]">ContextOps models a realistic enterprise assistant that must retrieve the right source, reject content the user cannot access, call only permitted tools, explain what it used, and produce evaluation signals for every run. The demo data is synthetic; the engineering constraints are not.</p><Link href="/work/enterprise-ai-ops-agent" className="mt-7 inline-flex rounded-full border border-[var(--ink)] px-4 py-2 text-sm font-semibold hover:bg-[var(--ink)] hover:text-[var(--bg)]">Read the full case study →</Link></div><div className="rounded-3xl border border-[var(--line)] bg-[var(--ink)] p-7 text-[var(--bg)] md:p-9"><p className="font-mono text-xs uppercase tracking-[0.14em] opacity-60">Evaluation target</p><p className="mt-5 text-5xl font-semibold tracking-[-0.05em]">≥ 0.90</p><p className="mt-2 text-sm opacity-70">grounded answer quality on the synthetic benchmark</p><div className="mt-8 border-t border-white/15 pt-6 text-sm leading-6 opacity-75">Hard gates: zero permission leaks, citations on material claims, reversible tool actions, and traceability per run.</div></div></div></div></section>

      <section className="border-b border-[var(--line)]"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><SectionHeading eyebrow="In production" title="Enterprise AI work at S&P Global." body="The portfolio does not reproduce internal systems or proprietary data. It shows the architecture patterns and deployment judgment behind the work." /><div className="mt-12">{experienceHighlights.map((x) => <article key={x.company} className="grid gap-8 rounded-3xl border border-[var(--line)] bg-[var(--surface)] p-7 md:grid-cols-[0.55fr_1.45fr] md:p-9"><div><p className="text-2xl font-semibold tracking-[-0.03em]">{x.company}</p><p className="mt-2 text-sm text-[var(--muted)]">{x.role}</p></div><div><p className="max-w-3xl text-lg leading-8">{x.body}</p><div className="mt-7 grid gap-3">{x.bullets.map((b) => <div key={b} className="flex gap-4 border-t border-[var(--line)] pt-4 text-sm leading-6 text-[var(--muted)]"><span className="font-mono text-[var(--signal)]">↳</span><p>{b}</p></div>)}</div></div></article>)}<div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-[var(--line)] bg-[var(--surface)] px-6 py-4 text-sm"><span><strong>Princeton University</strong> · B.S.E. Computer Science</span><span className="text-[var(--muted)]">Resume available directly to recruiting teams on request.</span></div></div></div></section>

      <section className="border-b border-[var(--line)]"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><div className="flex flex-col justify-between gap-7 md:flex-row md:items-end"><SectionHeading eyebrow="Build lab" title="Small agents, specific proof." body="Each side project isolates a capability that matters in forward-deployed work: permissions, solution design, ROI, incident response, and safe tool use." /><Link href="/labs" className="shrink-0 text-sm font-semibold underline decoration-[var(--line)] underline-offset-4">Open all labs →</Link></div><div className="mt-12 grid gap-4 lg:grid-cols-3">{labs.map((lab) => <Link href={`/labs#${lab.slug}`} key={lab.slug} className="group rounded-3xl border border-[var(--line)] bg-[var(--surface)] p-7 transition hover:-translate-y-1 hover:border-[var(--ink)]"><p className="font-mono text-[11px] uppercase tracking-[0.14em] text-[var(--signal)]">{lab.kicker}</p><h3 className="mt-5 text-2xl font-semibold tracking-[-0.03em]">{lab.title}</h3><p className="mt-4 text-sm leading-7 text-[var(--muted)]">{lab.summary}</p><div className="mt-7 flex flex-wrap gap-2">{lab.signals.slice(0, 3).map((s) => <span key={s} className="rounded-full bg-[var(--soft)] px-2.5 py-1 text-[11px]">{s}</span>)}</div><p className="mt-8 text-sm font-semibold">Run demo <span className="inline-block transition group-hover:translate-x-1">→</span></p></Link>)}</div></div></section>

      <section id="thinking" className="border-b border-[var(--line)]"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><SectionHeading eyebrow="How I think" title="Design principles for AI systems that people can actually trust." /><div className="mt-12 divide-y divide-[var(--line)] border-y border-[var(--line)]">{principles.map(([title, body], i) => <div key={title} className="grid gap-4 py-7 md:grid-cols-[80px_0.7fr_1.3fr] md:items-start"><span className="font-mono text-xs text-[var(--muted)]">0{i + 1}</span><h3 className="font-semibold">{title}</h3><p className="max-w-2xl text-sm leading-7 text-[var(--muted)]">{body}</p></div>)}</div></div></section>

      <section><div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><div className="rounded-[2rem] bg-[var(--ink)] px-7 py-12 text-[var(--bg)] md:px-12 md:py-16"><p className="font-mono text-xs uppercase tracking-[0.16em] opacity-60">Next deployment</p><h2 className="mt-5 max-w-4xl text-balance text-4xl font-semibold tracking-[-0.045em] md:text-6xl">Bring me the messy workflow, not the polished requirements.</h2><p className="mt-6 max-w-2xl text-base leading-7 opacity-70">I’m most useful where AI capability meets ambiguous business process, fragmented data, security constraints, and a real adoption target.</p><div className="mt-8 flex flex-wrap gap-3"><a href={`mailto:${site.email}`} className="rounded-full bg-[var(--bg)] px-5 py-3 text-sm font-semibold text-[var(--ink)]">Email me</a><a href={site.linkedin} target="_blank" rel="noreferrer" className="rounded-full border border-white/25 px-5 py-3 text-sm font-semibold">LinkedIn ↗</a></div></div></div></section>
    </main>
  );
}
