import Link from "next/link";
import { ArchitectureDiagram } from "@/components/architecture-diagram";
import { SectionHeading } from "@/components/section-heading";
import { capabilities, engineeringSurface, experienceHighlights, impact, labs, principles, site } from "@/lib/site";

export default function Home() {
  return (
    <main>
      <section className="grid-field border-b border-[var(--line)]">
        <div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28 lg:py-32">
          <div className="reveal max-w-6xl">
            <div className="mb-8 flex flex-wrap items-center gap-2 text-xs">
              <span className="rounded-full border border-[var(--line)] bg-[var(--surface)] px-3 py-1.5">New York, NY</span>
              <span className="rounded-full border border-[var(--line)] bg-[var(--surface)] px-3 py-1.5">Software engineering</span>
              <span className="rounded-full border border-[var(--line)] bg-[var(--surface)] px-3 py-1.5">Applied AI</span>
              <span className="rounded-full border border-[var(--line)] bg-[var(--surface)] px-3 py-1.5">Production systems</span>
            </div>
            <h1 className="max-w-5xl text-balance text-5xl font-semibold tracking-[-0.055em] sm:text-6xl md:text-7xl lg:text-[84px] lg:leading-[0.98]">I turn ambiguous problems into production software.</h1>
            <p className="mt-8 max-w-3xl text-balance text-lg leading-8 text-[var(--muted)] md:text-xl">Full-stack products, AI systems, data integrations, and automation—from understanding the real problem to designing, shipping, evaluating, and operating the solution.</p>
            <div className="mt-9 flex flex-wrap gap-3"><Link href="#builds" className="btn-primary rounded-full px-5">Explore production builds ↘</Link><Link href="/labs" className="btn-secondary">Run working AI labs</Link></div>
          </div>
          <div className="mt-20 grid gap-px overflow-hidden rounded-3xl border border-[var(--line)] bg-[var(--line)] md:grid-cols-4">{impact.map((item) => <div key={item.label} className="bg-[var(--surface)] p-6 md:p-7"><p className="text-3xl font-semibold tracking-[-0.04em]">{item.value}</p><p className="mt-2 text-sm font-medium">{item.label}</p><p className="mt-4 text-xs leading-5 text-[var(--muted)]">{item.detail}</p></div>)}</div>
        </div>
      </section>

      <section className="border-b border-[var(--line)]"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><SectionHeading eyebrow="Engineering range" title="I care about the whole system, not a single layer." body="The work I want to be judged on spans product UI, backend services, AI/retrieval, data movement, security, evaluation, and production operations." /><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{engineeringSurface.map((item) => <article key={item.label} className="rounded-3xl border border-[var(--line)] bg-[var(--surface)] p-6"><p className="font-mono text-[11px] uppercase tracking-[0.14em] text-[var(--signal)]">{item.label}</p><h3 className="mt-4 text-xl font-semibold tracking-[-0.03em]">{item.value}</h3><p className="mt-4 text-sm leading-6 text-[var(--muted)]">{item.proof}</p></article>)}</div><div className="mt-6 grid gap-px overflow-hidden rounded-3xl border border-[var(--line)] bg-[var(--line)] md:grid-cols-2">{capabilities.map((cap) => <article key={cap.title} className="bg-[var(--surface)] p-7 md:p-9"><h3 className="text-xl font-semibold tracking-[-0.025em]">{cap.title}</h3><p className="mt-4 max-w-xl text-sm leading-7 text-[var(--muted)]">{cap.body}</p><div className="mt-6 flex flex-wrap gap-2">{cap.proof.map((item) => <span key={item} className="rounded-full bg-[var(--soft)] px-3 py-1.5 text-xs">{item}</span>)}</div></article>)}</div></div></section>

      <section id="builds" className="border-b border-[var(--line)]"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><SectionHeading eyebrow="Public builds" title="Projects that solve an actual problem and expose the engineering behind them." body="The portfolio deliberately mixes live external data, server-side workflows, AI system design, evaluation, and production deployment instead of showing three variations of the same chatbot." />
        <div className="mt-12 grid gap-5 lg:grid-cols-2">
          <article className="rounded-3xl border border-[var(--line)] bg-[var(--surface)] p-7 md:p-9"><div className="flex items-center justify-between gap-3"><p className="font-mono text-xs uppercase tracking-[0.14em] text-[var(--signal)]">LIVE · REAL PUBLIC DATA</p><span className="rounded-full bg-[var(--soft)] px-3 py-1 text-[11px]">No API key</span></div><h3 className="mt-5 text-3xl font-semibold tracking-[-0.04em]">AI Policy Radar</h3><p className="mt-4 text-sm leading-7 text-[var(--muted)]">Tracks recent U.S. federal AI-related regulatory documents from the Federal Register API. The product handles live external data, server-side fetching, caching, normalization, provenance, upstream failure handling, and source-linked results.</p><div className="mt-6 flex flex-wrap gap-2">{["Next.js", "External APIs", "Caching", "Data normalization", "Provenance", "Production deployment"].map((x) => <span key={x} className="rounded-full bg-[var(--soft)] px-3 py-1.5 text-xs">{x}</span>)}</div><Link href="/projects/policy-radar" className="btn-primary mt-8 rounded-full px-5">Open live project →</Link></article>
          <article className="rounded-3xl border border-[var(--line)] bg-[var(--surface)] p-7 md:p-9"><div className="flex items-center justify-between gap-3"><p className="font-mono text-xs uppercase tracking-[0.14em] text-[var(--signal)]">WORKING · SERVER EXECUTED</p><span className="rounded-full bg-[var(--soft)] px-3 py-1 text-[11px]">3 workflows</span></div><h3 className="mt-5 text-3xl font-semibold tracking-[-0.04em]">Agent Systems Lab</h3><p className="mt-4 text-sm leading-7 text-[var(--muted)]">Three server-executed workflows demonstrate permission-aware retrieval, technical discovery and architecture, and AI incident response. Every run exposes tool purpose, decision logic, evidence, guardrails, and output metrics.</p><div className="mt-6 flex flex-wrap gap-2">{["Next.js API routes", "RAG", "Tool orchestration", "Guardrails", "Observability", "Evals"].map((x) => <span key={x} className="rounded-full bg-[var(--soft)] px-3 py-1.5 text-xs">{x}</span>)}</div><Link href="/labs" className="btn-secondary mt-8">Run the workflows →</Link></article>
        </div>
      </div></section>

      <section id="work" className="border-b border-[var(--line)]"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><SectionHeading eyebrow="Deep dive" title="ContextOps: permission-aware retrieval and agent tooling." body="This is one focused proof of production AI engineering—not the definition of the entire portfolio. It models how retrieval, authorization, tools, citations, and evaluation fit together when correctness and access boundaries matter." /><div className="mt-12"><ArchitectureDiagram /></div><div className="mt-8 grid gap-4 lg:grid-cols-[1.3fr_0.7fr]"><div className="rounded-3xl border border-[var(--line)] bg-[var(--surface)] p-7 md:p-9"><p className="font-mono text-xs uppercase tracking-[0.14em] text-[var(--signal)]">Engineering question</p><h3 className="mt-4 text-2xl font-semibold tracking-[-0.03em]">How do you answer useful questions without violating the user's authorization boundary?</h3><p className="mt-5 max-w-2xl text-sm leading-7 text-[var(--muted)]">The public build resolves a user security context, retrieves candidate evidence, filters restricted sources before answer composition, calls task-specific tools, and exposes the run for evaluation. The data is synthetic; the workflow executes on the server.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/labs#context-ops" className="btn-primary rounded-full px-5">Run ContextOps →</Link><Link href="/work/enterprise-ai-ops-agent" className="btn-secondary">Read system design →</Link></div></div><div className="rounded-3xl border border-[var(--line)] bg-[var(--ink)] p-7 text-white md:p-9"><p className="font-mono text-xs uppercase tracking-[0.14em] opacity-60">Release gates</p><p className="mt-5 text-4xl font-semibold tracking-[-0.05em]">Security before generation.</p><div className="mt-8 border-t border-white/15 pt-6 text-sm leading-6 opacity-75">Permission filtering, citations, reversible actions, inspectable traces, and regression checks are treated as system behavior—not prompt instructions.</div></div></div></div></section>

      <section className="border-b border-[var(--line)]"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><SectionHeading eyebrow="Production experience" title="Enterprise engineering at S&P Global." body="This section shows the scale and engineering judgment behind my professional work without reproducing proprietary systems or internal data." /><div className="mt-12">{experienceHighlights.map((x) => <article key={x.company} className="grid gap-8 rounded-3xl border border-[var(--line)] bg-[var(--surface)] p-7 md:grid-cols-[0.55fr_1.45fr] md:p-9"><div><p className="text-2xl font-semibold tracking-[-0.03em]">{x.company}</p><p className="mt-2 text-sm text-[var(--muted)]">{x.role}</p></div><div><p className="max-w-3xl text-lg leading-8">{x.body}</p><div className="mt-7 grid gap-3">{x.bullets.map((b) => <div key={b} className="flex gap-4 border-t border-[var(--line)] pt-4 text-sm leading-6 text-[var(--muted)]"><span className="font-mono text-[var(--signal)]">↳</span><p>{b}</p></div>)}</div></div></article>)}<div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-[var(--line)] bg-[var(--surface)] px-6 py-4 text-sm"><span><strong>Princeton University</strong> · B.S.E. Computer Science</span><span className="text-[var(--muted)]">Resume available directly to recruiting teams on request.</span></div></div></div></section>

      <section className="border-b border-[var(--line)]"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><div className="flex flex-col justify-between gap-7 md:flex-row md:items-end"><SectionHeading eyebrow="Working labs" title="Three problems, three different system behaviors." body="These are not static screenshots. Each workflow executes on the server and exposes what it did, why it did it, the evidence it used, and the engineering skills being demonstrated." /><Link href="/labs" className="shrink-0 text-sm font-semibold underline decoration-[var(--line)] underline-offset-4">Open all labs →</Link></div><div className="mt-12 grid gap-4 lg:grid-cols-3">{labs.map((lab) => <Link href={`/labs#${lab.slug}`} key={lab.slug} className="group rounded-3xl border border-[var(--line)] bg-[var(--surface)] p-7 transition hover:-translate-y-1 hover:border-[var(--ink)]"><p className="font-mono text-[11px] uppercase tracking-[0.14em] text-[var(--signal)]">{lab.kicker}</p><h3 className="mt-5 text-2xl font-semibold tracking-[-0.03em]">{lab.title}</h3><p className="mt-4 text-sm leading-7 text-[var(--muted)]">{lab.summary}</p><div className="mt-7 flex flex-wrap gap-2">{lab.skills.slice(0, 4).map((s) => <span key={s} className="rounded-full bg-[var(--soft)] px-2.5 py-1 text-[11px]">{s}</span>)}</div><p className="mt-8 text-sm font-semibold">Inspect workflow <span className="inline-block transition group-hover:translate-x-1">→</span></p></Link>)}</div></div></section>

      <section id="thinking" className="border-b border-[var(--line)]"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><SectionHeading eyebrow="How I think" title="Engineering principles that travel across products, AI, and infrastructure." /><div className="mt-12 divide-y divide-[var(--line)] border-y border-[var(--line)]">{principles.map(([title, body], i) => <div key={title} className="grid gap-4 py-7 md:grid-cols-[80px_0.7fr_1.3fr] md:items-start"><span className="font-mono text-xs text-[var(--muted)]">0{i + 1}</span><h3 className="font-semibold">{title}</h3><p className="max-w-2xl text-sm leading-7 text-[var(--muted)]">{body}</p></div>)}</div></div></section>

      <section><div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><div className="rounded-[2rem] bg-[var(--ink)] px-7 py-12 text-white md:px-12 md:py-16"><p className="font-mono text-xs uppercase tracking-[0.16em] opacity-60">What I want to work on</p><h2 className="mt-5 max-w-4xl text-balance text-4xl font-semibold tracking-[-0.045em] md:text-6xl">Hard product problems where software, AI, data, and people meet.</h2><p className="mt-6 max-w-2xl text-base leading-7 text-white/70">I’m interested in roles where I can own the technical path from ambiguity to production: understand the user, choose the right architecture, build across the stack, measure the result, and improve it in the field.</p><div className="mt-8 flex flex-wrap gap-3"><a href={`mailto:${site.email}`} className="btn-primary rounded-full px-5">Email me</a><a href={site.linkedin} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center rounded-full border border-white/30 px-5 py-3 text-sm font-semibold text-white transition hover:bg-white hover:text-black">LinkedIn ↗</a></div></div></div></section>
    </main>
  );
}
