import Link from "next/link";
import { ArchitectureDiagram } from "@/components/architecture-diagram";
import { LabPlayground } from "@/components/lab-playground";
import { SectionHeading } from "@/components/section-heading";

export const metadata = { title: "ContextOps — Enterprise AI Operations Agent", description: "A production-style case study covering permission-aware RAG, MCP-style tools, evaluation, observability, tradeoffs, and measurable workflow value." };

const tradeoffs = [
  ["Deterministic demo vs. live model", "The public experience defaults to deterministic execution so every reviewer gets a stable, free demo. Model adapters are intentionally separable from tool and policy contracts."],
  ["Pre-filter vs. post-filter permissions", "Authorization is applied before retrieval context reaches generation. Post-generation redaction is treated as a last line of defense, not the primary control."],
  ["Single agent vs. many agents", "One orchestrator with typed tools is easier to observe and evaluate. Specialized sub-agents are added only where task boundaries justify the extra coordination cost."],
  ["Quality vs. latency", "Retrieval and verification steps have explicit budgets. The system can skip expensive reranking when high-confidence metadata filters already narrow the answer space."],
];
const stack = [
  ["Experience", "Next.js 16.3 · React 19.2 · TypeScript · Tailwind 4.3"],
  ["Agent runtime", "Python · FastAPI · typed tool registry · deterministic provider adapter"],
  ["Retrieval", "Hybrid lexical / metadata demo retriever with permission pre-filtering"],
  ["Evaluation", "RAG triad concepts · policy tests · citation coverage · latency / cost accounting"],
  ["Deployment", "Vercel-ready web app · container-friendly Python service · GitHub Actions"],
];

export default function CaseStudy() {
  return <main>
    <section className="grid-field border-b border-[var(--line)]"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><Link href="/#work" className="text-sm text-[var(--muted)] hover:text-[var(--ink)]">← Back to work</Link><div className="mt-10 max-w-5xl"><p className="font-mono text-xs uppercase tracking-[0.18em] text-[var(--signal)]">Flagship case study · ContextOps</p><h1 className="mt-5 text-balance text-5xl font-semibold tracking-[-0.055em] sm:text-6xl md:text-7xl">A RAG agent designed for the part demos usually skip.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-[var(--muted)]">ContextOps is a public reference system for enterprise knowledge work: messy sources, permission boundaries, tool calls, citations, evals, observability, and an explicit business-value hypothesis.</p></div><div className="mt-12 grid gap-px overflow-hidden rounded-3xl border border-[var(--line)] bg-[var(--line)] md:grid-cols-4">{[["0","permission leaks","hard launch gate"],["100%","citation target","material claims"],["≥0.90","quality target","synthetic benchmark"],["$0","demo dependency","no paid API required"]].map(([v,l,d])=><div key={l} className="bg-[var(--surface)] p-6"><p className="text-3xl font-semibold tracking-[-0.04em]">{v}</p><p className="mt-2 text-sm font-medium">{l}</p><p className="mt-3 text-xs text-[var(--muted)]">{d}</p></div>)}</div></div></section>

    <section className="border-b border-[var(--line)]"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 md:grid-cols-[0.7fr_1.3fr] md:px-8 md:py-24"><div><p className="font-mono text-xs uppercase tracking-[0.16em] text-[var(--signal)]">01 · Problem</p></div><div className="max-w-3xl"><h2 className="text-3xl font-semibold tracking-[-0.04em]">Enterprise knowledge is not a clean chat corpus.</h2><div className="mt-6 space-y-5 text-base leading-8 text-[var(--muted)]"><p>Documents conflict. Ownership changes. Some sources are public, others are group-restricted. The same question may require retrieval, a permissions check, a structured lookup, and a human approval before any action is taken.</p><p>A useful system therefore needs to answer a larger question than “can the model generate a good response?” It needs to prove that the response came from allowed evidence, that tools behaved correctly, and that the workflow improved enough to justify deployment.</p></div></div></div></section>

    <section className="border-b border-[var(--line)]"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-24"><SectionHeading eyebrow="02 · Architecture" title="Policy first. Tools second. Generation last." body="The system treats identity, access, retrieval, tools, and evaluation as first-class runtime components." /><div className="mt-10"><ArchitectureDiagram /></div><div className="mt-8 grid gap-4 md:grid-cols-3">{[["Retrieve","Search synthetic enterprise sources using lexical signals, metadata, version context, and a permission pre-filter."],["Act","Expose bounded MCP-style tools with typed inputs, explicit write authority, idempotency, and human approval where needed."],["Evaluate","Score groundedness, relevance, policy compliance, citation coverage, tool correctness, latency, and estimated cost."]].map(([title,body])=><div key={title} className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-6"><h3 className="font-semibold">{title}</h3><p className="mt-3 text-sm leading-7 text-[var(--muted)]">{body}</p></div>)}</div></div></section>

    <section className="border-b border-[var(--line)]"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-24"><SectionHeading eyebrow="03 · Live proof" title="Run a permission-aware agent trace." /><div className="mt-10"><LabPlayground slug="context-ops" /></div></div></section>

    <section className="border-b border-[var(--line)]"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 md:grid-cols-2 md:px-8 md:py-24"><div><p className="font-mono text-xs uppercase tracking-[0.16em] text-[var(--signal)]">04 · Evaluation</p><h2 className="mt-4 text-3xl font-semibold tracking-[-0.04em]">The eval suite is part of the product definition.</h2><p className="mt-5 text-sm leading-7 text-[var(--muted)]">A golden set covers answerable questions, stale-source conflicts, denied-content requests, missing evidence, and unsafe write actions. RAG quality and agent behavior are scored separately so failures are diagnosable.</p></div><div className="rounded-3xl border border-[var(--line)] bg-[var(--surface)] p-6 md:p-8">{[["Context relevance","Did retrieval find evidence needed for this question?"],["Groundedness","Are answer claims supported by retrieved evidence?"],["Answer relevance","Did the response actually solve the user’s task?"],["Policy compliance","Was restricted context excluded before generation?"],["Tool correctness","Were tool arguments, authority, and outcomes valid?"],["Operational budget","Did the run meet latency and cost thresholds?"]].map(([m,q],i)=><div key={m} className={`${i ? "border-t border-[var(--line)]" : ""} py-4`}><div className="flex gap-5"><span className="font-mono text-xs text-[var(--signal)]">0{i+1}</span><div><p className="text-sm font-semibold">{m}</p><p className="mt-1.5 text-xs leading-5 text-[var(--muted)]">{q}</p></div></div></div>)}</div></div></section>

    <section className="border-b border-[var(--line)]"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-24"><SectionHeading eyebrow="05 · Tradeoffs" title="Architecture decisions I would defend in a design review." /><div className="mt-10 divide-y divide-[var(--line)] border-y border-[var(--line)]">{tradeoffs.map(([title,body])=><div key={title} className="grid gap-3 py-6 md:grid-cols-[0.7fr_1.3fr]"><h3 className="font-semibold">{title}</h3><p className="text-sm leading-7 text-[var(--muted)]">{body}</p></div>)}</div></div></section>

    <section className="border-b border-[var(--line)]"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 md:grid-cols-[0.8fr_1.2fr] md:px-8 md:py-24"><div><p className="font-mono text-xs uppercase tracking-[0.16em] text-[var(--signal)]">06 · Business value</p><h2 className="mt-4 text-3xl font-semibold tracking-[-0.04em]">ROI is modeled from the workflow, not from tokens.</h2></div><div className="space-y-6"><p className="text-base leading-8 text-[var(--muted)]">For a real deployment, I would baseline time spent locating policy, validating access, composing the answer, and escalating uncertain cases. The pilot value equation is driven by observed adoption × time saved × fully loaded labor cost, offset by inference, infrastructure, and operational review costs.</p><div className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-6 font-mono text-sm leading-7">annual_value = successful_runs × minutes_saved × labor_cost_per_minute<br />net_value = annual_value − model_cost − platform_cost − review_cost</div><p className="text-sm leading-7 text-[var(--muted)]">I would not publish a fabricated dollar figure for a synthetic project. The proof is the measurement framework and the ability to instrument a real pilot.</p></div></div></section>

    <section className="border-b border-[var(--line)]"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-24"><SectionHeading eyebrow="07 · Stack" title="Modern where it matters. Boring where reliability wins." /><div className="mt-10 overflow-hidden rounded-3xl border border-[var(--line)]">{stack.map(([layer,tech],i)=><div key={layer} className={`grid gap-3 bg-[var(--surface)] p-5 md:grid-cols-[0.35fr_1.65fr] ${i ? "border-t border-[var(--line)]" : ""}`}><p className="text-sm font-semibold">{layer}</p><p className="text-sm text-[var(--muted)]">{tech}</p></div>)}</div></div></section>

    <section><div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-24"><SectionHeading eyebrow="08 · Demo script" title="Two minutes: what I would show a hiring team." /><div className="mt-10 grid gap-4 md:grid-cols-4">{[["0:00–0:25","Frame the problem","Enterprise AI fails when retrieval, permissions, and actions are treated as afterthoughts. ContextOps makes those constraints visible."],["0:25–0:55","Run the denied-access case","Show identity resolution → policy guard → allowed metadata-only answer. Emphasize that restricted text never reaches generation."],["0:55–1:25","Show eval + trace","Point to citation coverage, groundedness, policy compliance, tool trace, and latency. Explain how a bad score routes into error analysis."],["1:25–2:00","Connect to business value","Explain the pilot baseline, time-saved model, rollout gates, and how field feedback becomes reusable architecture."]].map(([time,title,body])=><div key={time} className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-6"><p className="font-mono text-xs text-[var(--signal)]">{time}</p><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-3 text-xs leading-6 text-[var(--muted)]">{body}</p></div>)}</div></div></section>
  </main>;
}
