const deployedUrl = process.env.VERCEL_PROJECT_PRODUCTION_URL ? `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}` : undefined;
export const site = { name: "Harpreet Kaur", email: "harpreetkaur622@gmail.com", location: "New York, NY", github: "https://github.com/hkaur2001", linkedin: "https://www.linkedin.com/in/harpreet-kaur-0501/", tagline: "I build AI systems that survive contact with the enterprise.", url: process.env.NEXT_PUBLIC_SITE_URL ?? deployedUrl ?? "http://localhost:3000" };
export const impact = [
{ value: "40K+", label: "enterprise users", detail: "Systems built for organization-scale adoption, not isolated demos." },
{ value: "8+", label: "enterprise integrations", detail: "Knowledge and workflow systems spanning multiple internal platforms." },
{ value: "500K+", label: "knowledge assets", detail: "Production pipelines designed around messy, changing enterprise content." },
{ value: "End-to-end", label: "delivery ownership", detail: "Discovery → architecture → implementation → monitoring → rollout." }];
export const capabilities = [
{ title: "Agent & tool systems", body: "I design agents around explicit tools, bounded authority, observability, and failure handling—not just a system prompt and a loop.", proof: ["Tool contracts", "MCP-style interfaces", "Human approval gates", "Retries + fallbacks"] },
{ title: "Retrieval that respects reality", body: "Enterprise RAG is a data, permissions, freshness, and evaluation problem before it is a vector database problem.", proof: ["Hybrid retrieval", "Metadata filters", "Access controls", "Source-grounded answers"] },
{ title: "Evaluation as infrastructure", body: "I use offline and online evaluation loops to turn model behavior into a measurable engineering surface.", proof: ["RAG triad", "LLM-as-judge", "Golden datasets", "Failure taxonomy"] },
{ title: "Business-value engineering", body: "The deployment is not finished when the model answers correctly. I connect technical choices to adoption, cycle time, labor saved, and risk.", proof: ["ROI models", "Workflow baselines", "Adoption metrics", "Cost / latency budgets"] }];
export const principles = [["Start with the workflow", "The model is one component. I first map the user, decision, data, action, and failure cost."], ["Make authority explicit", "An agent should know what it may read, what it may write, and when a human must approve."], ["Evaluate the system, not just the model", "Retrieval quality, tool correctness, latency, cost, and user trust all determine production quality."], ["Design for change", "Models, APIs, schemas, and enterprise content all move. Good AI systems make those changes observable and reversible."]];
export const experienceHighlights = [{ company: "S&P Global", role: "Software & Platform Engineer · AI systems", body: "Built and productionized enterprise AI infrastructure around Spark Assist, connecting live knowledge and workflow systems while partnering across engineering, IT, security, and business teams.", bullets: ["Owned integration patterns spanning 8+ enterprise systems and more than 500K knowledge assets.", "Built reusable onboarding, routing, validation, monitoring, and failure-recovery patterns for enterprise knowledge pipelines.", "Designed permission-aware collection behavior, metadata filtering, and multi-collection retrieval patterns for large-scale internal AI experiences.", "Translated ambiguous internal use cases into shipped systems designed for an enterprise user population of 40K+."] }];
export type LabSlug = "context-ops" | "solution-architect" | "incident-commander";
export const labs: Array<{ slug: LabSlug; kicker: string; title: string; summary: string; signals: string[] }> = [
{ slug: "context-ops", kicker: "Flagship · RAG + tools + evals", title: "ContextOps", summary: "A permission-aware enterprise knowledge agent that retrieves evidence, calls bounded tools, cites its answer, and scores its own run.", signals: ["RAG", "MCP-style tools", "Access policy", "Evals", "Observability"] },
{ slug: "solution-architect", kicker: "Applied AI · GTM", title: "Solution Architect Agent", summary: "Turns a messy customer brief into discovery gaps, an implementation architecture, a quantified value hypothesis, and a pilot plan.", signals: ["Discovery", "ROI", "Architecture", "Technical selling", "Pilot design"] },
{ slug: "incident-commander", kicker: "Reliability · Agent ops", title: "Incident Commander", summary: "Triages a production AI incident through tools, separates evidence from hypotheses, and proposes safe reversible actions.", signals: ["Tool use", "Observability", "Runbooks", "Guardrails", "Human-in-loop"] }];
