import Link from "next/link";
import { SentinelConsole } from "@/components/sentinel-console";
import { runDeterministicSafetyEvals } from "@/lib/sentinel/evals";
import { publicScenario, SENTINEL_SCENARIOS } from "@/lib/sentinel/scenarios";
import { TOOL_DEFINITIONS } from "@/lib/sentinel/tool-registry";

export const metadata = {
  title: "Sentinel — AI Production Incident Response Platform",
  description: "A production-oriented incident response agent with adaptive tool use, evidence-backed diagnosis, deterministic policy enforcement, human approval, observability, and evaluations.",
};

const architecture = [
  ["01", "Incident simulator", "Injects reproducible failures across services, metrics, logs, deployments, database events, and dependencies."],
  ["02", "Investigation agent", "Uses OpenAI Responses API tool calling to decide what evidence to request next based on intermediate observations."],
  ["03", "Tool gateway", "Exposes bounded read-only tools with explicit schemas, permissions, risk, timeout, retry, and audit metadata."],
  ["04", "Knowledge layer", "Provides runbooks and prior incidents with service metadata; the standalone backend includes a PostgreSQL + pgvector schema."],
  ["05", "Policy engine", "Deterministic code—not the model—decides whether a requested action is allowed and whether human approval is mandatory."],
  ["06", "Approval + remediation", "Production-impacting actions pause for a human. The public demo only modifies simulated infrastructure."],
  ["07", "Security boundary", "Tool output is untrusted data. Prompt-injection-like log content is labeled, never promoted to instruction priority."],
  ["08", "Observability", "Captures tool sequence, evidence IDs, latency, model calls, tokens, cost estimate, state, and security signals per run."],
  ["09", "Evaluation", "Separates deterministic safety/governance tests from live-model quality so metrics are measurable rather than decorative."],
] as const;

export default function SentinelPage() {
  const scenarios = SENTINEL_SCENARIOS.map(publicScenario);
  const evalSummary = runDeterministicSafetyEvals();
  const liveConfigured = Boolean(process.env.OPENAI_API_KEY);

  return (
    <main>
      <section className="grid-field border-b border-[var(--line)]">
        <div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28">
          <div className="flex flex-wrap items-center gap-2 text-xs"><span className="rounded-full border border-[var(--line)] bg-[var(--surface)] px-3 py-1.5">Live OpenAI reasoning</span><span className="rounded-full border border-[var(--line)] bg-[var(--surface)] px-3 py-1.5">Adaptive tool calling</span><span className="rounded-full border border-[var(--line)] bg-[var(--surface)] px-3 py-1.5">Human approval</span><span className="rounded-full border border-[var(--line)] bg-[var(--surface)] px-3 py-1.5">Production safety</span></div>
          <p className="mt-10 font-mono text-xs uppercase tracking-[0.16em] text-[var(--signal)]">Flagship build · production AI systems</p>
          <h1 className="mt-5 max-w-5xl text-balance text-5xl font-semibold tracking-[-0.055em] sm:text-6xl md:text-7xl lg:text-[80px] lg:leading-[0.98]">Sentinel investigates incidents instead of waiting for a prompt-perfect human.</h1>
          <p className="mt-7 max-w-3xl text-lg leading-8 text-[var(--muted)] md:text-xl">A production-oriented incident-response platform that correlates logs, metrics, deployments, database diagnostics, runbooks, and service health; builds evidence-backed hypotheses; proposes bounded remediation; and routes risky actions through deterministic policy and human approval.</p>
          <div className="mt-8 flex flex-wrap gap-3"><a href="#demo" className="btn-primary rounded-full px-5">Run a live incident ↓</a><a href="#architecture" className="btn-secondary">Inspect architecture</a><Link href="https://github.com/hkaur2001/harpreet_portfolio/tree/main/sentinel" target="_blank" className="btn-secondary">Open implementation ↗</Link></div>
        </div>
      </section>

      <section className="border-b border-[var(--line)]"><div className="mx-auto max-w-7xl px-5 py-16 md:px-8 md:py-20"><div className="grid gap-3 md:grid-cols-4">{[
        ["Agent model", liveConfigured ? "OpenAI routed" : "Fallback ready", liveConfigured ? "Server secret detected; visitors can run bounded live investigations." : "The deterministic engine keeps the demo functional without a provider."],
        ["Tool surface", `${TOOL_DEFINITIONS.length} bounded tools`, "Logs, metrics, deployments, DB diagnostics, health, runbooks, git changes, incident history."],
        ["Safety suite", `${evalSummary.policyPasses}/${evalSummary.totalCases} policy checks`, `${evalSummary.approvalBypasses} approval bypasses across deterministic governance cases.`],
        ["Simulator", `${SENTINEL_SCENARIOS.length} incident classes`, "Database, API, release, memory, network, schema, auth, queue, service, and ambiguous failures."],
      ].map(([label, value, body]) => <div key={label} className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-5"><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-[var(--muted)]">{label}</p><p className="mt-3 text-2xl font-semibold tracking-[-0.03em]">{value}</p><p className="mt-3 text-xs leading-5 text-[var(--muted)]">{body}</p></div>)}</div></div></section>

      <section id="demo" className="border-b border-[var(--line)]"><div className="mx-auto max-w-[1480px] px-5 py-20 md:px-8 md:py-24"><div className="mb-10 max-w-4xl"><p className="font-mono text-xs uppercase tracking-[0.16em] text-[var(--signal)]">Interactive production simulation</p><h2 className="mt-4 text-balance text-4xl font-semibold tracking-[-0.045em] md:text-6xl">Inject a failure. Watch the investigation adapt.</h2><p className="mt-5 text-base leading-7 text-[var(--muted)]">The incident data is synthetic so the environment is safe and reproducible. In live mode, the model genuinely chooses which tools to call and what to investigate next; tool outputs and policy enforcement are real server-side code paths. Remediation is always simulated.</p></div><SentinelConsole scenarios={scenarios} liveConfigured={liveConfigured} evalSummary={evalSummary} /></div></section>

      <section id="architecture" className="border-b border-[var(--line)]"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><p className="font-mono text-xs uppercase tracking-[0.16em] text-[var(--signal)]">System architecture</p><h2 className="mt-4 max-w-4xl text-balance text-4xl font-semibold tracking-[-0.045em] md:text-6xl">The model is one component. The platform owns the blast radius.</h2><p className="mt-5 max-w-3xl text-base leading-7 text-[var(--muted)]">Sentinel uses one primary Investigation Agent instead of a theatrical swarm. Specialized capabilities are tools and services. That keeps state, evaluation, cost, and authority boundaries easier to reason about.</p><div className="mt-10 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{architecture.map(([number, title, body]) => <article key={number} className="rounded-3xl border border-[var(--line)] bg-[var(--surface)] p-6"><div className="flex items-center justify-between"><span className="font-mono text-xs text-[var(--signal)]">{number}</span><span className="text-[var(--muted)]">→</span></div><h3 className="mt-7 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{body}</p></article>)}</div></div></section>

      <section className="border-b border-[var(--line)]"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><div className="grid gap-8 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="font-mono text-xs uppercase tracking-[0.16em] text-[var(--signal)]">Tool contract</p><h2 className="mt-4 text-4xl font-semibold tracking-[-0.045em]">The LLM never gets raw infrastructure access.</h2><p className="mt-5 text-sm leading-7 text-[var(--muted)]">Every tool declares purpose, permission, risk, timeout, retry policy, and a strict input schema. The public runtime exposes only bounded read operations during investigation. The standalone implementation also publishes the same surface through an MCP server.</p></div><div className="overflow-hidden rounded-3xl border border-[var(--line)] bg-[var(--surface)]"><div className="grid grid-cols-[1fr_auto_auto] border-b border-[var(--line)] bg-[var(--soft)] px-5 py-3 text-[10px] font-semibold uppercase tracking-[0.12em]"><span>Tool</span><span>Permission</span><span className="ml-5">Risk</span></div>{TOOL_DEFINITIONS.map((tool) => <div key={tool.name} className="grid gap-2 border-b border-[var(--line)] px-5 py-4 last:border-b-0 md:grid-cols-[1fr_auto_auto] md:items-center"><div><code className="text-sm font-semibold">{tool.name}()</code><p className="mt-1 text-xs text-[var(--muted)]">{tool.purpose}</p></div><code className="text-[10px] text-[var(--muted)]">{tool.permission}</code><span className="md:ml-5 rounded-full bg-[var(--soft)] px-2.5 py-1 text-[10px]">{tool.risk}</span></div>)}</div></div></div></section>

      <section className="border-b border-[var(--line)]"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><div className="grid gap-8 lg:grid-cols-2"><div className="rounded-3xl bg-[var(--ink)] p-7 text-white md:p-9"><p className="font-mono text-xs uppercase tracking-[0.14em] text-white/60">Security design</p><h2 className="mt-5 text-4xl font-semibold tracking-[-0.045em]">The model recommends. Deterministic systems enforce.</h2><div className="mt-7 space-y-4 text-sm leading-6 text-white/75">{["Logs and tool outputs are explicitly treated as untrusted observations, so embedded instructions do not inherit authority.", "Production-impacting actions are never exposed as investigation tools; they go through a separate policy endpoint.", "Risk levels 2–3 in production require approval, and rollback is always approval-gated.", "The ambiguous scenario intentionally includes a malicious log instruction; the correct behavior is to label it and escalate rather than obey it."].map((item) => <p key={item}>{item}</p>)}</div></div><div className="rounded-3xl border border-[var(--line)] bg-[var(--surface)] p-7 md:p-9"><p className="font-mono text-xs uppercase tracking-[0.14em] text-[var(--signal)]">Evaluation discipline</p><h2 className="mt-5 text-4xl font-semibold tracking-[-0.045em]">Metrics are separated by what they actually prove.</h2><p className="mt-5 text-sm leading-7 text-[var(--muted)]">I do not label deterministic fixtures as “91% model accuracy.” The deployed dashboard reports real per-run model/tool/token/cost telemetry, while the repeatable CI suite measures deterministic policy, approval, schema, and injection controls. Live-model root-cause accuracy belongs to a separately executed model eval dataset.</p><div className="mt-7 grid grid-cols-2 gap-3"><div className="rounded-xl bg-[var(--bg)] p-4"><p className="text-3xl font-semibold">{evalSummary.policyPasses}%</p><p className="mt-1 text-xs text-[var(--muted)]">policy pass rate</p></div><div className="rounded-xl bg-[var(--bg)] p-4"><p className="text-3xl font-semibold">{evalSummary.toolSchemaCoverage}%</p><p className="mt-1 text-xs text-[var(--muted)]">tool contract coverage</p></div><div className="rounded-xl bg-[var(--bg)] p-4"><p className="text-3xl font-semibold">{evalSummary.approvalBypasses}</p><p className="mt-1 text-xs text-[var(--muted)]">approval bypasses</p></div><div className="rounded-xl bg-[var(--bg)] p-4"><p className="text-3xl font-semibold">{evalSummary.injectionDetected}/{evalSummary.injectionCases}</p><p className="mt-1 text-xs text-[var(--muted)]">injection fixtures detected</p></div></div></div></div></div></section>

      <section><div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><p className="font-mono text-xs uppercase tracking-[0.16em] text-[var(--signal)]">Repository depth</p><h2 className="mt-4 max-w-4xl text-balance text-4xl font-semibold tracking-[-0.045em] md:text-6xl">The live demo is only the front door.</h2><p className="mt-5 max-w-3xl text-base leading-7 text-[var(--muted)]">The repository includes a standalone FastAPI service, MCP tool server, PostgreSQL/pgvector schema, simulator fixtures, Docker Compose environment, evaluation tests, security and architecture documentation, and Terraform reference infrastructure so the project can be discussed from product UI down to deployment controls.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="https://github.com/hkaur2001/harpreet_portfolio/tree/main/sentinel" target="_blank" className="btn-primary rounded-full px-5">Inspect Sentinel source ↗</Link><Link href="/" className="btn-secondary">Back to portfolio</Link></div></div></section>
    </main>
  );
}
